name: CI Test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '*.md'
    - '.github/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade Chrome browser
        run: |
            sudo apt-get update
            sudo apt-get --only-upgrade install google-chrome-stable
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '14.18.2'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run lib tests
        run: npm run test:lib
      - name: Run e2e tests
        run: npm run e2e
